### ISSUE TITLE
New test UI does not log and disable buttons once the client goes off

### ISSUE THREAD

**Issue by Harkishen-Singh** [bench-routes/bench-routes#114]
**Describe the bug**
`http://localhost:9090/test` is used to test **bench-routes**. However, during testing, if the br service crashes, this is not logged in the logger UI in the front-end. Further, once the connection is lost, a banner should be displayed in the top of the screen like `Connection lost. Retrying in x seconds.`. When the retry continues to fail, the failure count (suppose say y) can be displayed inside a bracket like `Connection lost. Retrying(y) in x seconds.`

Also, when the client goes off, the button events should be disabled in order to prevent false logging.

**Comment by prajwal714** [comment]
Interested in the issue for GSSOC'20

**Comment by Harkishen-Singh** [comment]
You can go head with this issue. Do you want this to be assigned?

**Comment by prajwal714** [comment]
Yeah. Assign it to me. Thanks @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
Sure. You can start working on this. Should not take longer than 4 days at max.

**Comment by muskankhedia** [comment]
We aren't using the `http://localhost:9090/test` for testing our routes anymore. So, this should be good to close.
