### ISSUE TITLE
Insert null values for blocks that dont exists in UI

### ISSUE THREAD

**Issue by Harkishen-Singh** [bench-routes/bench-routes#242]
currently, if a block does not exist, the graph is formed instead of discontinuing for those points. This can be done by inserting `null` in those places in the frontend - v1.1

**Comment by ganeshpatro321** [comment]
Tell me the steps to reproduce @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
This needs to be implemented in the go code.

**Comment by Harkishen-Singh** [comment]
This is the problem of the a graph. Right now, if you monitor for, say 5 mins and stop bench-routes, and again start after 30 mins, the graph is formed, connecting the first 5 mins with 30 mins, being continuous in nature. This is wrong.

Instead, the behaviour should be such that, the graph should be continuous only in the five minutes region. The graph should then not exist for next 30 mins, and then again start from when there is monitoring data (all graphs in current UI have this issue).

**Comment by Rits1272** [comment]
May I work on this issue @Harkishen-Singh ?

**Comment by Harkishen-Singh** [comment]
Definitely @Rits1272. That would be awesome.

**Comment by ruddi10** [comment]
@Rits1272  are you working on this or can I take up this issue?

**Comment by Rits1272** [comment]
Yeah I am working @ruddi10 !

**Comment by Rits1272** [comment]
Hello @Harkishen-Singh! Here is my approach to solving this issue: When the bench-routes start, we can get the timestamp of the last block that was added of all the metrics (last time when the bench-routes was stopped). After that, we can calculate the delta in time of the current time and last timestamp and then can populate the JSON file accordingly with null block. 

Should I go ahead with this approach?

**Comment by Harkishen-Singh** [comment]
that is good, but i fear too much network traffic. anyways, we can have this, but make sure to add a flag as `experimental` in the code block you implement

**Comment by Rits1272** [comment]
Sure @Harkishen-Singh I will make a PR with this approach and try to write a benchmark it possible:)
