### ISSUE TITLE
UI for routes input for monitoring

### ISSUE THREAD

**Issue by Harkishen-Singh** [bench-routes/bench-routes#257]
Provide UI for taking routes as input for monitoring screen.

**Comment by Harkishen-Singh** [comment]
Right now, the input section is in the sidebar. This was done was debugging purposes. We should remove it from the sidebar to a floating-button in the monitoring screen.

**Comment by Anuragtech02** [comment]
Hey @Harkishen-Singh I'd like to give this a try! Could you please assign this to me ?

**Comment by Harkishen-Singh** [comment]
@Anuragtech02 please go ahead. Assigning wouldn't be the best thing for us but you can always voluntarily comment based on your interest and let others know.

**Comment by Anuragtech02** [comment]
> @Anuragtech02 please go ahead. Assigning wouldn't be the best thing for us but you can always voluntarily comment based on your interest and let others know.
Thanks @Harkishen-Singh ! I'll start working on this.
