### ISSUE TITLE
Support for querier component in frontend for variable time-based querying

### ISSUE THREAD

**Issue by Harkishen-Singh** [bench-routes/bench-routes#258]
The current querying in the frontend happens for recent 1-hour samples. The querier in br supports time-based querying that is capable of fetching samples within a given time-range. The UI for this is to be designed.

**Comment by ruddi10** [comment]
@Harkishen-Singh would like to work on this issue but can you explain this feature a bit more?

**Comment by muskankhedia** [comment]
Sure. Go ahead.

**Comment by ruddi10** [comment]
Can either of you clarify this issue a bit more it will be helpful @muskankhedia @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
If you see the current graphs being formed, they are being formed for a time-range of 1 hour only.

https://github.com/bench-routes/bench-routes/blob/88675e90866f0f83cc11d31417b37d99226547a8/dashboard/v1.1/src/pages/Dashboard/SystemMetrics.tsx#L125

This should be made changeable. This will be done via an interactive UI so that the user can select a start date and time and an end date and time of a query to be performed. The corresponding graphs will be shown to the user. This needs to happen across al the graphs in the UI. So in order to keep this clean, either make a wrapper or something similar so that the code is not redundant.

**Comment by ruddi10** [comment]
Okk @Harkishen-Singh will give it a try btw #332 have implemented a shared chart component so will you be merging it I think that can act as a wrapper so it will be better if we incorporate that in that shared component. What do you think?

**Comment by ruddi10** [comment]
@muskankhedia @Harkishen-Singh ?

**Comment by muskankhedia** [comment]
@ruddi10 You can start working on this issue independently as merging PR #332 might take some time.

**Comment by ruddi10** [comment]
Ok

**Comment by Harkishen-Singh** [comment]
@ruddi10 #332 just got merged. If this could be of any help.

**Comment by ruddi10** [comment]
Sure though I have implemented a seperate solution will be pushing it after few changes
