### ISSUE TITLE
saving route responses?

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/bench-routes#275]
The USP of Postman  app is to check for responses from specific routes and test them. What if we would do it in a better way? Since we are already monitoring routes data and storing the required ping or jitter values, what if we store the responses too in some specific (deterministic) interval? That way all the user has to do is search in the table, also not always memorise the params, headers, body, etc. Also, what I had in mind is that we can export these route responses as an organisation in some website/hub for people to search and see, just like collections. 

### For example:

zairza-website has made an API to share a list of best movies given a paticular year. The request to the url would look like this:
```
url: /api/movies/
params: "2019"
headers: "Content-Type: "application/json""
```

and a sample response would look like:
```
"data": {
     "2019": [
         "movie1", "movie2", "movie3"
      ]
}
```

If we plan to monitor the response at some deterministic interval and save it somewhere, the next time the user will just search for the route and BAM! There would be an entry `Last response: monitored 2 days ago via bench-routes...`. Also, zairza as an organisation can decide to make this API public so that people could see sample requests and sample responses on their API. This can even work as a documentation example and even a testing tool based on feedbacks.

**Comment by Harkishen-Singh** [comment]
This will be good to have.

**Comment by Harkishen-Singh** [comment]
I think this is out of the scope of the project. Our aim is for monitoring, not response conformance.
