### ISSUE TITLE
UI crashes when opening routes in Monitoring screen

### ISSUE THREAD

**Issue by Harkishen-Singh** [bench-routes/bench-routes#331]
**Describe the bug**
UI crashes when opening some routes for seeing paste monitoring performance in the monitoring screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. When bench-routes is on, switch on the monitoring in monitoring screen.
2. After getting the results on monitoring screen, click on arrow.
3. Some routes (on the monitoring screen) will crash the UI
4. This is because ping, jitter values are not available for that route.

**Expected behaviour**
For such routes that have no data for ping, etc., the UI should show `No graph` or related 

**Desktop (please complete the following information):**
 - OS: Linux 
 - Version: f43565 (commit)

**Comment by ruddi10** [comment]
@Harkishen-Singh  kindly assign this issue to me
