### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by dev117uday** [bench-routes/bench-routes#336]
**Describe the bug**
After building the image, when i tried to start the container error 

```
panic: exec: "journalctl": executable file not found in $PATH
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `docker build -t bench-routes . `
2. `docker run -p 9990:9990 -it bench-routes`

**Screenshots**
Output when running `docker run -p 9990:9990 -it bench-routes`
![image](https://user-images.githubusercontent.com/49728410/110816899-c7552380-82b1-11eb-800d-37c3aebd2430.png)

**System info :**
 - OS: Ubuntu 20.04
 - commit : f4356551

**Additional context**
journalctl is systemd's logging service [here](https://www.loggly.com/ultimate-guide/using-journalctl/#:~:text=Journalctl%20is%20a%20utility%20for,log%20messages%20processed%20by%20journald.) The base image used in the docker is alpine which doesnt implement systemd to init service but uses openRC [more reference, read the last line](https://en.wikipedia.org/wiki/Alpine_Linux#Features)

_Unlike many distributions, including Debian, Ubuntu, RHEL, Arch Linux and CentOS, Alpine does not use systemd._

I could be wrong about this.

**Comment by dev117uday** [comment]
Also `.dockerignore` is missing in the repo, starting the build unnecessarily copy the node_modules to it.

**Comment by Harkishen-Singh** [comment]
Ah, alpine does not support journalctl. It has its own story of syslog. We can make journalctl disable if its not supported on a particular platform. That would fix this issue. Would you mind doing that?

To summarise the tasks require to update current stuff:
1. Update go version in docker to `1.16.1`
2. .dockerignore addition for the above purpose (possible make a different folder with dockerfile and the .ignore file?)
3. disable journal metrics if system does not have journalctl supported

Thank you @dev117uday for reporting this.

**Comment by dev117uday** [comment]
@Harkishen-Singh I would love to take up this issue

**Comment by dev117uday** [comment]
@Harkishen-Singh please review the pr #335
