### ISSUE TITLE
[GSOC] Revamping UI: styled-component proposal

### ISSUE THREAD

**Issue by jugshaurya** [bench-routes/bench-routes#338]
#### Describe
- I think to maintain the modularity of code and clean components code-wise. [styled-component](https://styled-components.com/) is a very good option to go with. 
- Agree?, let me know, I have worked with styled-components on my [personal project](https://github.com/jugshaurya/showcase). It helped me in code management and modularity of components. I would like to work on it.  @muskankhedia @Harkishen-Singh 

- If agree let me know, and assign it to me. I would love to work on it.

**Comment by Harkishen-Singh** [comment]
You can propose the details in your proposal, based on your understanding and how it helps the project. We will discuss that there. But a proposal cannot be accepted if you don't have experience with the GSoC project. Hence, contributions are the current need of the time.

**Comment by Vishv07** [comment]
@Harkishen-Singh  Is it necessary to have previous experience of GSOC in order to accept the proposal.

**Comment by muskankhedia** [comment]
@Vishv07 No, it is not at all necessary. But I will advise you to contribute to other issues in the project as that will help you to understand the code in a better way and at the same time help us to know you better.

**Comment by Vishv07** [comment]
Thanks got it @muskankhedia
