### ISSUE TITLE
The last row in the monitoring screen gets hidden

### ISSUE THREAD

**Issue by muskankhedia** [bench-routes/bench-routes#341]
**Describe the bug**
The details in the last row of the table in the monitoring screen gets hidden.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the monitoring screen in the UI
2. Scroll down to the bottom of the page

**Expected behaviour**
The details in the last row should be clearly visible.

**Screenshots**
<img width="1773" alt="Screenshot 2021-03-13 at 12 48 35 PM" src="https://user-images.githubusercontent.com/36980003/111023268-0a241200-83fe-11eb-9c23-f0a986fc8f19.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: 6c35419

**Comment by ruddi10** [comment]
I have fixed this issue kindly dont work on it pushing the commit but some error is there due to husky discussiong on it
