### ISSUE TITLE
Add the name of the route opened at the top

### ISSUE THREAD

**Issue by muskankhedia** [bench-routes/bench-routes#344]
**Describe the bug**
In the monitoring screen, a user can click on the forward arrow button to check on the details of a particular route. But due to the absence of any heading of which route has been clicked, it creates confusion and misleading for the user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Monitoring screen.
2. Click on the forward button on any route.

**Expected behaviour**
A heading with the route name to be displayed at the top.

**Screenshots**
<img width="1780" alt="Screenshot 2021-03-13 at 3 00 14 PM" src="https://user-images.githubusercontent.com/36980003/111025950-9853c480-840d-11eb-9768-b6825c67c7cb.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: 44fac7d9e707616731a9d129613e1b6532c54406

**Comment by haardikdharma10** [comment]
Hi @muskankhedia, I would like to work on this task. Can you help me out roughly with the files involved?

**Comment by Vishv07** [comment]
Can I work upon this issue?

**Comment by Harkishen-Singh** [comment]
@Vishv07 please go ahead.

**Comment by ruddi10** [comment]
> @Vishv07 please go ahead.

I have fixed it @Vishv07 kindly solve some other issue

**Comment by muskankhedia** [comment]
@ruddi10 @Vishv07 I hope you both might have received a mail from the discussion group. Please go through it properly. I would like to summarise that again here.

Kindly make a comment on an issue before you start working on it and if someone else has made the comment, do respect that and work on that issue only if the comment made earlier has been a quite long time or he/she is inactive. You can know if the person is inactive by just making another comment asking about the update of their work in the issue. Kindly follow these rules, as this will help us provide all the students with an equal chance else unwillingly we have to close the PR of the one who breaks the rule.

**Comment by ruddi10** [comment]
> @ruddi10 @Vishv07 I hope you both might have received a mail from the discussion group. Please go through it properly. I would like to summarise that again here.
> 
> Kindly make a comment on an issue before you start working on it and if someone else has made the comment, do respect that and work on that issue only if the comment made earlier has been a quite long time or he/she is inactive. You can know if the person is inactive by just making another comment asking about the update of their work in the issue. Kindly follow these rules, as this will help us provide all the students with an equal chance else unwillingly we have to close the PR of the one who breaks the rule.

I apolozise for this @muskankhedia will make sure to follow this in future.

**Comment by muskankhedia** [comment]
Thank you @ruddi10.
