### ISSUE TITLE
Responsiveness of Monitoring screen

### ISSUE THREAD

**Issue by Tushar3099** [bench-routes/bench-routes#346]
**Describe the bug**
In the monitoring screen, when the screen is resized, the columns are not resized according to the screen, due to which the columns are getting hidden.

**To Reproduce**
1. Go to the Monitoring Screen.
2. Resize the Window(change the width).

**Expected behavior**
The contents of the Monitoring screen should resize according to the window size.

**Screenshots**
![Screenshot from 2021-03-13 18-28-22](https://user-images.githubusercontent.com/51849085/111030974-3e61f780-842b-11eb-9d96-5e23f6242ebf.png)

**Desktop (please complete the following information):**
 - OS: Linux(Ubuntu 20.04)
 - Version : f43565 (commit)

**Additional context**
This is the first issue I am raising here. If there is some mistake, please guide me. I want to work on this issue.

**Comment by Harkishen-Singh** [comment]
If you want to take this up, you are most welcome.

**Comment by Pratik1234agarwal** [comment]
I would like to take this up. If it's still awailable
