### ISSUE TITLE
Tooltip text is not visible in dark mode.

### ISSUE THREAD

**Issue by rishav4101** [bench-routes/bench-routes#356]
**Describe the bug**
Tooltip text is not visible in dark mode due to the text being light.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Dashboard'
2. Switch to 'Dark mode'
3. Hover on graphs so as 'tooltip' appears

**Expected behaviour**
Tooltip should also be in dark mode so that it is readable.

**Screenshots**
![eajjg](https://user-images.githubusercontent.com/55195287/111075078-3c239a00-850c-11eb-94c6-f6386ec71536.png)
![Untitledsgd-1](https://user-images.githubusercontent.com/55195287/111075084-3d54c700-850c-11eb-8b16-0333c4281597.png)

**Desktop (please complete the following information):**
 - OS: linux(ubuntu)
 - Version 20.04

**Comment by rishav4101** [comment]
I would like to take up this issue.

**Comment by Harkishen-Singh** [comment]
You are welcome to take that up.
