### ISSUE TITLE
Feat: Improve Input Label UI

### ISSUE THREAD

**Issue by sachdeva-shrey** [bench-routes/bench-routes#358]
**Is your feature request related to a problem? Please describe.**
The current implementation of the `Add Label` feature in `QuickInput` can be improved for a few reasons:
1. Hard to distinguish `Add a Label` text as button at the first glance.
2. Overflow scrollbar at the bottom.
3. Spacing issues.

**Describe the solution you'd like**
Fix the above mentioned issues.

**Screenshot**
![Screenshot from 2021-03-15 14-16-30](https://user-images.githubusercontent.com/47667325/111127620-09c07e00-859a-11eb-9b82-a1f024f6c14c.png)
![Screenshot from 2021-03-15 14-33-41](https://user-images.githubusercontent.com/47667325/111128936-8142dd00-859b-11eb-909b-42e0753db805.png)

**Additional context**
I'd like to work on this.

**Comment by kaiwalyakoparkar** [comment]
Hey, I would like to work on this issue. Could you please guide me with this issue

**Comment by sachdeva-shrey** [comment]
@kaiwalyakoparkar I'm sorry, I've already made a PR for this issue here https://github.com/bench-routes/bench-routes/pull/359.

**Comment by kaiwalyakoparkar** [comment]
Ok! could you suggest me an issue?
