### ISSUE TITLE
Guidance for GSOC 2021

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [bench-routes/bench-routes#363]
Hey,
I am a new contributor and I want to work on **" Revamping the UI "** as it is in the GSOC 2021 idealist and also it interests me a lot. Can I get some guidance so that I can contribute to this project even after the GSOC duration?

**Comment by Harkishen-Singh** [comment]
Please avoid making issues for these topics. We have mailing lists and community chat where questions like these can be asked.

I will have to close this issue as this is not the best place for asking.
