### ISSUE TITLE
Theme is not persistent

### ISSUE THREAD

**Issue by ruddi10** [bench-routes/bench-routes#367]
**Feature**
Currently on refreshing the dark or light mode preference resets rather we need to make it persistent

**Comment by muskankhedia** [comment]
@ruddi10 Thank you for the issue. One small feedback whenever you create an issue add a screenshot or gif or video. This will help everyone to understand the issue in a better way at the same time will be a good reference in the long run.

**Comment by ruddi10** [comment]
@muskankhedia will make sure to that
