### ISSUE TITLE
Radio Buttons in Quick Input page freezes

### ISSUE THREAD

**Issue by Rits1272** [bench-routes/bench-routes#369]
**Describe the bug**
In the `Quick Input`, radio buttons of `Header` and `Params` tends to freeze after hitting the `Test and Save` button

**To Reproduce**
1. Go to the `Quick Input` page
2. Enter any valid URL
3. Click `Test and Save`
4. Now check `Header` and `Params` radio buttons
5. Again click `Test and Save`
6. Now try to uncheck the `Header` and `Params` radio button

**Expected behavior**
The radio buttons should be working as expected. That is when the user unchecks the radio button, it should be unchecked.

https://user-images.githubusercontent.com/44135362/111307599-b163ac00-867f-11eb-8471-91b2c23b5879.mp4

 - OS: ubuntu 20.04

**Comment by sachdeva-shrey** [comment]
Hey @Rits1272, are you working on this issue?

**Comment by Rits1272** [comment]
You may go ahead with this issue @sachdeva-shrey :)
