### ISSUE TITLE
Add: Pagination in monitoring table.

### ISSUE THREAD

**Issue by rishav4101** [bench-routes/bench-routes#370]
**Is your feature request related to a problem? Please describe.**
When monitoring routes increases in large numbers it could become difficult to scroll through and look for a route.

**Describe the solution you'd like**
Implementing pagination view in Matrix table in monitoring page would be a better user experience. This can be implemented using the Pagination component of material-ui.

**Screenshot of proposed solution**
![mob](https://user-images.githubusercontent.com/55195287/111328883-a6ffdd00-8694-11eb-93d9-f461dbf03b9f.jpg)

**Comment by rishav4101** [comment]
I would like to work on this feature.

**Comment by Harkishen-Singh** [comment]
@rishav4101 please go ahead. I thought we had that but its very strange that we were missing it. Anyways, thank you for reporting. Please do note that we only fetch those time-series from API that are require in the current page only, and not all time-series in the matrix.

**Comment by rishav4101** [comment]
Yeah sure. Thank you so much.
