### ISSUE TITLE
make Error

### ISSUE THREAD

**Issue by shreyaskhadapkar** [bench-routes/bench-routes#377]
`make update`

> echo "updating dependencies ..."

>"updating dependencies ..."
>go get -u ./...
>github.com/bench-routes/bench-routes/src/metrics/system
>src\metrics\system\system.go:132:18: now.Cached undefined (type *memory.Stats has no field or method Cached)
>make: *** [Makefile:3: update] Error 2

**Comment by Tushar3099** [comment]
@shreyaskhadapkar Can you please explain the error?
How to produce the error, and what is the expected outcome.
`make update` command is working well in my OS(Linux Ubuntu 20.04)

**Comment by shreyaskhadapkar** [comment]
@Tushar3099 I followed steps as instructed from the documention. I successfully installed Golang and  cloned the repo . While running the command `make run` I encountered this error. Currently I'm on windows 10.


I'm new to open-source so any kind of help is appreciated.
Thank You in advance!!

**Comment by shreyaskhadapkar** [comment]
> @shreyaskhadapkar are you using a windows system? We have seen other users face this issue when they were on the windows platform. Using the WSL in windows helped them solve the issue. 

Yes, I'm using windows system. I'll try installing WSL and let you know. Thank You!!

**Comment by shreyaskhadapkar** [comment]
> @shreyaskhadapkar are you using a windows system? We have seen other users face this issue when they were on the windows platform. Using the WSL in windows helped them solve the issue. 

@Harkishen-Singh Yes, I'm using windows system. I'll try installing WSL and let you know. Thank You!!

**Comment by shreyaskhadapkar** [comment]
@Harkishen-Singh  I tried enabling WSL in my windows system. The same error occurs again. Any help? or am I doing it wrong?

**Comment by Harkishen-Singh** [comment]
Ah, we as such never supported windows. Could you run it in some Linux distro?

**Comment by shreyaskhadapkar** [comment]
I have successfully installed the project locally!! Thanks for the help!!
Is docker thing needed to be done?? or I can start contributing directly based on local setup?

**Comment by Harkishen-Singh** [comment]
You can always do locally. Feel free to close the issue if everything is fine.

**Comment by shreyaskhadapkar** [comment]
Yes. Thank You!!
