### ISSUE TITLE
Add: Search bar in monitoring table.

### ISSUE THREAD

**Issue by rishav4101** [bench-routes/bench-routes#384]
**Requested feature**
Adding a search bar in the monitoring table could make the work of searching a route much easier for users.

**Describe the solution you'd like**
We could add a search bar in the monitoring table using the npm package 'material-ui-search-bar', which is very efficient and easy to use.

**Screenshot of proposed feature**
![searchbar](https://user-images.githubusercontent.com/55195287/111619757-f3215d80-880b-11eb-94f8-aedfdb11af42.png)

**Comment by rishav4101** [comment]
@Harkishen-Singh I would like to work on this feature.

**Comment by muskankhedia** [comment]
@rishav4101 Go ahead.
