### ISSUE TITLE
Create dockerignore file

### ISSUE THREAD

**Issue by Anuragtech02** [bench-routes/bench-routes#385]
**Describe the bug**
Dockerfile is huge right now (380MB), we can add a `dockerignore` which will ignore files such as `node_modules` which in this case is the reason for such a large size.

**Expected behaviour**
Docker build context should be significantly less in size.

**Screenshots**
### Before Adding `.dockerignore` size was `389.4MB`
![SS_BEFORE](https://user-images.githubusercontent.com/55744578/111625670-21ef0200-8813-11eb-96a1-87d919a6a519.png)

### After adding `.dockerignore` size became `40.86MB`
![SS_AFTER](https://user-images.githubusercontent.com/55744578/111626091-9b86f000-8813-11eb-8163-db5013243716.png)

**Desktop (please complete the following information):**
 - OS: [Debain 9 (Stretch)]

**Comment by Anuragtech02** [comment]
I've created the dockerfile and will push it once the issue is approved.

**Comment by muskankhedia** [comment]
@Anuragtech02 Yes you can go ahead with this.

**Comment by Anuragtech02** [comment]
@muskankhedia Now that the PR is merged shall I close this issue ?
