### ISSUE TITLE
Graphs/Charts in dark mode.

### ISSUE THREAD

**Issue by rishav4101** [bench-routes/bench-routes#386]
**Is your feature request related to a problem? Please describe.**
Graphs/charts still remain in light mode when the webpage is changed to dark mode.

**Describe the solution you'd like**
I would like to change the graphs/charts to dark mode too, with making use of 'dark-mode' variable stored in localstorage.

**Describe alternatives you've considered**
If the use of localstorage is not preferred we could pass the darkMode prop to children components from BaseLayout.tsx, which can used to change themes of those components. I have used this method in PR #357. 

**Additional context**
Adding this feature shall deem the PR #357 void, as 'theme' option to Apexcharts caters to both the needs.

**Screenshot of proposed feature**
![darkgraph](https://user-images.githubusercontent.com/55195287/111656268-6046ea00-8830-11eb-946d-11a3d3733a60.png)
![ano](https://user-images.githubusercontent.com/55195287/111678448-4e704180-8846-11eb-9f46-47d0b5817e08.png)

**Comment by rishav4101** [comment]
@Harkishen-Singh @muskankhedia I would like to work on this feature.

**Comment by ruddi10** [comment]
@rishav4101 I have implemented dark-mode variable in one of the pr and its merged so yes I think you can use that

**Comment by ruddi10** [comment]
But I feel that here one cant see the contrast and different shades that are necessary to interpret the graphs so I think you can also think of some better contrast

**Comment by rishav4101** [comment]
@ruddi10 Yes I have used localstorage for now. Passing props is just an alternative. 
About contrast, I think that can be adjusted. I have attached another Screenshot where there are different colors in the graph and it's looking fine in my opinion, please have another look at it. The slight modifications if needed can be done by modifying the colors of the graph.

**Comment by muskankhedia** [comment]
> @Harkishen-Singh @muskankhedia I would like to work on this feature.

@rishav4101 Sure. Please go ahead.
