### ISSUE TITLE
Bug: Deleting Route from Config Screen breaks UI

### ISSUE THREAD

**Issue by sachdeva-shrey** [bench-routes/bench-routes#387]
**Describe the bug** 
Deleting a route from the config screen (`/configurations`) deletes the selected route but also breaks the UI. 

**To Reproduce** 
Steps to reproduce the behaviour: 
1. Go to `/configurations`
 2. Delete a route 
 3. The UI breaks 
 4. See error: `Unhandled Rejection (TypeError): setConfigRoutes is not a function` 
 
 **Expected behaviour** 
 The UI should not break and a confirmation should be shown confirming that the route is deleted.
 
  **Screenshots** 
  
![Screenshot from 2021-03-18 23-56-39](https://user-images.githubusercontent.com/47667325/111678269-1c5edf80-8846-11eb-9932-9a6b77d713b8.png) ![Screenshot from 2021-03-19 00-02-05](https://user-images.githubusercontent.com/47667325/111679072-f0902980-8846-11eb-8195-9a74ef45367e.png)

**Comment by sachdeva-shrey** [comment]
I would like to work on this issue.

**Comment by muskankhedia** [comment]
@sachdeva-shrey Sure, Go ahead.
