### ISSUE TITLE
remove that ugly border from quick-input icon

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/bench-routes#390]
Appears when we click on the quick-input button.

![Image](https://user-images.githubusercontent.com/26324376/111752886-9bffa500-886c-11eb-895b-e2ac4af31161.png)

*P.S. See bottom-right*

**Comment by ruddi10** [comment]
Will work on it

**Comment by ptechofficial** [comment]
hey, i've worked on a similar issue before. Can i work on this? I'll send a PR by tonight.

**Comment by ruddi10** [comment]
I am working on it kindly look for some other issue @ptechofficial

**Comment by ptechofficial** [comment]
> I am working on it kindly look for some other issue @ptechofficial 

yeah okay.
