### ISSUE TITLE
Replace Matrix table with Material Table

### ISSUE THREAD

**Issue by ruddi10** [bench-routes/bench-routes#396]
#### Describe
We can implement the Matrix table the same way we have implemented the config table that way the code will be consistent and a bit cleaner. Currently we are using MaterialTable component for making table of configuration page however thats not true for the table on Monitoring page.

**Comment by ruddi10** [comment]
@muskankhedia  @Harkishen-Singh what are your thoughts on this any particular reason for the different implementation? If not I would like to give this a try.

**Comment by Tushar3099** [comment]
@ruddi10 It would be amazing if you can explain your suggestion a bit more.

**Comment by aquibbaig** [comment]
Let's drop this issue since we'd be taking up a new table component definition in v2.
