### ISSUE TITLE
Quick input Icon hides

### ISSUE THREAD

**Issue by Tushar3099** [bench-routes/bench-routes#399]
**Describe the bug**
In the configure screen the Quick-input icon at the bottom-right gets hidden under the configuration table.

**To Reproduce**
1. Go to configure screen.
2. You can notice the hidden Quick-input icon

**Expected behavior**
The quick-input icon should be over the table.

**Screenshots**
![Screenshot from 2021-03-20 06-01-16](https://user-images.githubusercontent.com/51849085/111856441-b317c300-8950-11eb-98b2-20c8c45f95d6.png)

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 20.04
 - Version 80796c2 commit

**Comment by Tushar3099** [comment]
There is a simple fix. I want to work on this.

**Comment by muskankhedia** [comment]
@Tushar3099 This is basically because of the screen resolution. Even if you add `z-index` property to view it above the table, the pagination key will start hiding. What do you think about this?

**Comment by Tushar3099** [comment]
@muskankhedia IMHO I think that the design itself will create more problems in other places: like in dashboard its getting hidden by the graph :
![Screenshot from 2021-03-20 19-30-29](https://user-images.githubusercontent.com/51849085/111871954-ca879800-89b2-11eb-9dd9-e268791e563f.png)
We can have other designs so that the Quick-input icon won't collide with any other component :
- We can place the quick input icon to the bottom left where it won't collide with other components.
- We can place a small arrow on the bottom right, hovering on which, the quick-input icon will appear.
what are your views on this?

**Comment by muskankhedia** [comment]
@Tushar3099 I feel the second option will be a better approach for implementing it.

**Comment by Tushar3099** [comment]
@muskankhedia Thanks for the reply. I'll make a PR following the second option ASAP.
