### ISSUE TITLE
Showing selected Tests in Sidebar

### ISSUE THREAD

**Issue by Tushar3099** [bench-routes/bench-routes#400]
**Describe the bug**
When we select any test from the Test Tab, the sidebar doesn't highlight which test we have selected.

**To Reproduce**
1. Select any test from the sidebar.
2. You can see the selected test won't get highlighted.

**Expected behavior**
The selected test should get highlighted.

**Screenshots**
![Screenshot from 2021-03-20 08-13-04](https://user-images.githubusercontent.com/51849085/111857299-8797d700-8956-11eb-9074-42398c379f09.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Version 80796c2 commit

**Comment by Tushar3099** [comment]
I want to work on this issue if approved.

**Comment by muskankhedia** [comment]
@Tushar3099 Please go ahead. Also try fixing the same bug when the sidebar is in collapsed form.

**Comment by Tushar3099** [comment]
@muskankhedia Sure, I will do the prescribed changes too.
