### ISSUE TITLE
"Tests" menu in the sidebar is non-functional when sidebar is minimized

### ISSUE THREAD

**Issue by anwersayeed** [bench-routes/bench-routes#411]
**Describe the bug**
When we minimize the sidebar, all other menus like "Dashboard", "Monitoring", "Quick Input" and "Config" are functional except "Tests".

**To Reproduce**
      1. Minimize the sidebar by clicking on the hamburger.
      2. Click on the "Tests" icon.
      3. You can see, nothing happens when we click on the "Tests" icon.

**Expected behaviour**
Tests menu options should appear.

**Screenshots**
![2021-03-22 18_41_19-Bench-routes](https://user-images.githubusercontent.com/57287988/111994894-5417a100-8b3e-11eb-9be3-b07b20b1f79b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by prathameshbhalekar** [comment]
can i work on this issue?

**Comment by anwersayeed** [comment]
I created this issue and I want to work on this, please assign this issue to me?
