### ISSUE TITLE
Menu color in Dark Mode

### ISSUE THREAD

**Issue by robin828** [bench-routes/bench-routes#412]
**Describe the bug**
In the dashboard, there are three different types of graphs. In graphs, we have the different options on the right top corner. The most right icon( hamburger icon) opens a new small window that is not properly visible in dark mode.

1. Go to 'Dashboard in dark mode'
2. Click on 'hamburger icon'
3. See an error

**Expected behavior**
The background color of that window should be the same as the theme color.

![Screenshot 2021-03-22 at 6 51 45 PM](https://user-images.githubusercontent.com/61390860/111996089-ae653180-8b3f-11eb-8746-7567ea520685.png)

**Comment by robin828** [comment]
I want to work on this issue if approved.

**Comment by muskankhedia** [comment]
@robin828 Thank you for the issue but this issue has already been resolved in #389. Hence, closing it.

**Comment by robin828** [comment]
I am talking about this bug. see the difference between light mode and dark mode.

below one is dark mode
![Screenshot 2021-03-23 at 2 44 58 AM](https://user-images.githubusercontent.com/61390860/112059590-09b81380-8b82-11eb-85ff-bd9d11cbe0f9.png)

below one is a light mode
![Screenshot 2021-03-23 at 2 44 41 AM](https://user-images.githubusercontent.com/61390860/112059664-218f9780-8b82-11eb-963c-72abeef88b32.png)


And while I am researching this bug I get one more bug of the same type. 

below one is dark mode
![Screenshot 2021-03-23 at 2 43 54 AM](https://user-images.githubusercontent.com/61390860/112059841-69aeba00-8b82-11eb-87bc-fee9cebfa9b7.png)

![Screenshot 2021-03-23 at 2 44 09 AM](https://user-images.githubusercontent.com/61390860/112059875-76cba900-8b82-11eb-85af-bf7efcabb359.png)

**Comment by robin828** [comment]
I think that there still some bugs left I send some pictures on the same
issue please have a look.
Thanks and regards
