### ISSUE TITLE
feat: Make dark mode persist on page refresh

### ISSUE THREAD

**Issue by snehh** [bench-routes/bench-routes#440]
**Is your feature request related to a problem? Please describe.**
Currently, when the page is refreshed while on dark mode, it reverts back to light instead of remembering the earlier choice. This is especially a problem when viewing the page at night.

**Describe the solution you'd like**
I would like to use local storage to remember the selection so that the users can have a better experience, and the page will reload on the earlier mode the user was on.

**Addional Context**
![bench-routes issue dark mode reload](https://user-images.githubusercontent.com/63251826/112747260-c9b5be00-8fd1-11eb-801e-660b55b7ee10.gif)

**Comment by snehh** [comment]
If approved, I would like to work on this

**Comment by ruddi10** [comment]
@snehh  I think it was already implemented by me and merged

**Comment by ruddi10** [comment]
go to localhost 3000 after running make view-v1.1

**Comment by snehh** [comment]
Oh alright will check it out

**Comment by aquibbaig** [comment]
I dont think we'd be taking up any more "dark mode" issues as we are moving away from this version of dashboard, please see other issues, Thanks!
