### ISSUE TITLE
the name dark-mode is not appropriate

### ISSUE THREAD

**Issue by Anuragtech02** [bench-routes/bench-routes#461]
**Describe the bug**
The item name that we're using for toggling dark mode in the application i.e. `dark-mode` is not appropriate. This is how we're currently handling dark mode `localStorage.getItem('dark-mode') === 'true'`. The problem with this is that the term `dark-mode` is very generic and other applications might interfere/modify this which will change the behaviour of our application. 

**To Reproduce**
Use any application which also has the same technique and same name for togging dark mode. I created my own little application and tested. 

**Expected behaviour**
It should be something more appropriate/accurate like `bench-routes-dark-mode` or `br-dark-mode` so that it is different from others. 

**Screenshots**
![Screenshot from 2021-04-05 16-33-11](https://user-images.githubusercontent.com/55744578/113567752-d1f2a680-962c-11eb-9df5-25b669f1ebe8.jpg)

I'd work on this if the issue is approved.

**Comment by aquibbaig** [comment]
Hmm, sorry but we won't be opening any more issues with the dark mode.
