### ISSUE TITLE
Unable to connect dashboard to the server

### ISSUE THREAD

**Issue by satyaarthchhabra** [bench-routes/bench-routes#506]
**Describe the bug**
Hi , i am not  able to connect my dashboard with the backend .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to bench-routes backend folder
2. type "wsl"
3. type "make run"

**Expected behaviour**
a  bacckend server should start 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/56510402/134006456-c392360d-9ab5-4697-bcbf-13cd556f3e5b.PNG)

error logs :
compiling go-code and executing bench-routes
echo "using 9990 as default service listener port"
using 9990 as default service listener port
go run src/*.go 9990
level=info ts=2021-09-17T20:00:06.055Z caller=main.go:45 msg=configuration out="[{sample-google 5s https www.google.com /search get map[Content-Type:json] map[q:bench-routes] map[]}]"
level=info ts=2021-09-17T20:00:06.055Z caller=main.go:53 msg="launching machine routine"
level=info ts=2021-09-17T20:00:06.062Z caller=main.go:67 msg="launching monitor routine"
level=debug ts=2021-09-17T20:00:06.065Z caller=api.go:53 msg="Updated API domain map"
level=info ts=2021-09-17T20:00:06.065Z caller=main.go:117 msg="Listening at :9990"
level=error ts=2021-09-17T20:00:07.233Z caller=main.go:161 msg="running machine" error="running machine: job: sample-google: error running ping : socket: permission denied"
exit status 1

**Comment by aquibbaig** [comment]
Thanks for opening this issue, will be looking into this, currently assigning myself

**Comment by aquibbaig** [comment]
@ruddi10 What's your local config.yml on the backend?

<img width="1242" alt="Screenshot 2021-09-21 at 9 23 59 PM" src="https://user-images.githubusercontent.com/26324376/134204824-bafd6e45-8632-44e0-8ad3-43a2e129d222.png">

The parameters being sent with the request are:

```
name=/search&start=2021-09-21T14:53:38.917Z&end=2021-09-21T15:53:38.918Z&step=15
```

**Comment by ruddi10** [comment]
@aquibbaig can you please have a look at the request get-domain-entities as that's the one responsible for getting the entities and there its showing network error in your case, also I can see the request has some error as its having red text.
As for my config.yml its same as the bench routes master branch one

**Comment by satyaarthchhabra** [comment]
hi is this issue resolved @aquibbaig @ruddi10

**Comment by aquibbaig** [comment]
@satyaarthchhabra The issue on your end seems to be different, can you do a simple ping command on your terminal and display the results here? just do a `ping www.google.com`

**Comment by aquibbaig** [comment]
@ruddi10 The issue is tracked in #507

**Comment by satyaarthchhabra** [comment]
hey i thought that wsl was not working great for me so i used the installation process via docker and while i run  this command docker build -t bench-routes .  an error  came here are its log 
[+] Building 442.9s (16/18)
 => [internal] load build definition from Dockerfile                                                       0.2s 
 => => transferring dockerfile: 658B                                                                       0.0s 
 => [internal] load .dockerignore                                                                          0.1s 
 => => transferring context: 272B                                                                          0.0s 
 => [internal] load metadata for docker.io/library/centos:centos8                                          4.3s 
 => [ 1/14] FROM docker.io/library/centos:centos8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbde  140.7s 
 => => resolve docker.io/library/centos:centos8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55b  0.1s 
 => => sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177 762B / 762B                 0.0s 
 => => sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc 529B / 529B                 0.0s 
                  1.2s                                                                   .14kB             0.0s 
 => [ 6/14] WORKDIR /src/github.com/bench-routes/bench-routes                            83.52MB         119.2s 
                  0.1s                                                                                    19.6s 
 => [ 7/14] COPY . /src/github.com/bench-routes/bench-routes                                               1.3s 
                  0.3s                                                                                     1.1s 
 => [ 8/14] RUN cd $GOPATH/src/github.com/bench-routes/bench-routes/src && go get -v ./..                 82.1s .                15.0s                                                                                   187.2s 
 => [ 9/14] RUN go build $GOPATH/src/github.com/bench-routes/bench-routes/src/main.go                      1.0s 
                  2.0s                                                                                     1.2s 
 => [10/14] RUN mv main bench-routes                                                                       0.1s 
                  0.7s                                                                                     0.3s 
 => [11/14] RUN npm install -g yarn                                                      .                15.0s 
                  7.1s                                                                                     2.0s 
 => ERROR [12/14] RUN cd dashboard/v1.1/ && yarn install && yarn run build                                 0.7s 
                  0.6s                                                                                     7.1s 
------                                                                                                     0.6s 
 > [12/14] RUN cd dashboard/v1.1/ && yarn install && yarn run build:
#16 0.554 /bin/sh: line 0: cd: dashboard/v1.1/: No such file or directory
------
executor failed running [/bin/sh -c cd dashboard/v1.1/ && yarn install && yarn run build]: exit code: 1                                                                           : exit code: 1

hope you find it useful @aquibbaig

**Comment by ruddi10** [comment]
> @ruddi10 The issue is tracked in #507

So there is some issue with the backend right ? As I think it was stopping suddenly

**Comment by ruddi10** [comment]
> hey i thought that wsl was not working great for me so i used the installation process via docker and while i run this command docker build -t bench-routes . an error came here are its log
> [+] Building 442.9s (16/18)
> => [internal] load build definition from Dockerfile 0.2s
> => => transferring dockerfile: 658B 0.0s
> => [internal] load .dockerignore 0.1s
> => => transferring context: 272B 0.0s
> => [internal] load metadata for docker.io/library/centos:centos8 4.3s
> => [ 1/14] FROM docker.io/library/centos:centos8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbde 140.7s
> => => resolve docker.io/library/centos:centos8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55b 0.1s
> => => sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177 762B / 762B 0.0s
> => => sha256:a1801b843b1bfaf77c501e7a6d3f709401a1e0c83863037fa3aab063a7fdb9dc 529B / 529B 0.0s
> 1.2s .14kB 0.0s
> => [ 6/14] WORKDIR /src/github.com/bench-routes/bench-routes 83.52MB 119.2s
> 0.1s 19.6s
> => [ 7/14] COPY . /src/github.com/bench-routes/bench-routes 1.3s
> 0.3s 1.1s
> => [ 8/14] RUN cd $GOPATH/src/github.com/bench-routes/bench-routes/src && go get -v ./.. 82.1s . 15.0s 187.2s
> => [ 9/14] RUN go build $GOPATH/src/github.com/bench-routes/bench-routes/src/main.go 1.0s
> 2.0s 1.2s
> => [10/14] RUN mv main bench-routes 0.1s
> 0.7s 0.3s
> => [11/14] RUN npm install -g yarn . 15.0s
> 7.1s 2.0s
> => ERROR [12/14] RUN cd dashboard/v1.1/ && yarn install && yarn run build 0.7s
> 0.6s 7.1s
> ------ 0.6s
> 
> > [12/14] RUN cd dashboard/v1.1/ && yarn install && yarn run build:
> > #16 0.554 /bin/sh: line 0: cd: dashboard/v1.1/: No such file or directory
> 
> executor failed running [/bin/sh -c cd dashboard/v1.1/ && yarn install && yarn run build]: exit code: 1 : exit code: 1
> 
> hope you find it useful @aquibbaig

@satyaarthchhabra I will recommend to use Linux system for bench-routes if it's possible

**Comment by satyaarthchhabra** [comment]
that was not a big thing @ruddi10  just you have to remove some lines from the docker file. will make a pull request soon .

**Comment by ruddi10** [comment]
> that was not a big thing @ruddi10 just you have to remove some lines from the docker file. will make a pull request soon .

Kindly open an issue first and then make the corresponding PR fixing that

**Comment by aquibbaig** [comment]
@satyaarthchhabra Yeah, since the dashboard doesn't ship with this repo, it invalidates the dockerfile. Updating that would be good help

**Comment by aquibbaig** [comment]
@satyaarthchhabra btw, the error that you have mentioned in this issue tells me that for some reason `ping` command wasn't able to execute due to a permission error. Well, this can be due to the firewall blocking connections, or your connection itself might be the issue. Doing things "docker way" seems to be a good approach here

**Comment by satyaarthchhabra** [comment]
i got the same errors even with docker

**Comment by aaaaayushh** [comment]
> that was not a big thing @ruddi10 just you have to remove some lines from the docker file. will make a pull request soon .

I'm facing the same issue. Could you please tell which lines have to be edited in the Dockerfile?

**Comment by aaaaayushh** [comment]
@aquibbaig this issue persists with both the docker and the bare metal installation.  Is there any workaround for this?

**Comment by aaaaayushh** [comment]
> @aaaaayushh Are you on windows? If yes, can you do a regular `ping google.com` on your terminal and let me know what it says

No, I'm on linux. The issue was that I was restricted to make ping requests. Running
 `sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"` before running `make run` fixed the issue.
However, I'm still getting a network error on the application and would appreciate some help in fixing that
![Screenshot from 2021-10-15 11-44-14](https://user-images.githubusercontent.com/55553065/137440837-660865a3-5f67-4ffe-9c4b-cf0b300bfdb9.png)

**Comment by ruddi10** [comment]
@aaaaayushh  can you please show the response of get domain entities endpoint as the component that is showing network error actually fetches the data from this endpoint

**Comment by ruddi10** [comment]
> @aaaaayushh Awesome! I can see that a request to `/query-entity` returns a 404. May I know what's the error message?

@aquibbaig this is handled in the frontend

**Comment by aaaaayushh** [comment]
@ruddi10  this is the response of the first get domain entities
> > @aaaaayushh Are you on windows? If yes, can you do a regular `ping google.com` on your terminal and let me know what it says
> 
> No, I'm on linux. The issue was that I was restricted to make ping requests. Running `sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"` before running `make run` fixed the issue. However, I'm still getting a network error on the application and would appreciate some help in fixing that ![Screenshot from 2021-10-15 11-44-14](https://user-images.githubusercontent.com/55553065/137440837-660865a3-5f67-4ffe-9c4b-cf0b300bfdb9.png)

And here's the response for the second one
![Screenshot from 2021-10-15 23-53-10](https://user-images.githubusercontent.com/55553065/137534803-1fa9b59c-048e-4a1b-b7cc-62fc23f459c4.png)

**Comment by ruddi10** [comment]
> @ruddi10 this is the response of the first get domain entities
> 
> > > @aaaaayushh Are you on windows? If yes, can you do a regular `ping google.com` on your terminal and let me know what it says
> > 
> > 
> > No, I'm on linux. The issue was that I was restricted to make ping requests. Running `sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"` before running `make run` fixed the issue. However, I'm still getting a network error on the application and would appreciate some help in fixing that ![Screenshot from 2021-10-15 11-44-14](https://user-images.githubusercontent.com/55553065/137440837-660865a3-5f67-4ffe-9c4b-cf0b300bfdb9.png)
> 
> And here's the response for the second one ![Screenshot from 2021-10-15 23-53-10](https://user-images.githubusercontent.com/55553065/137534803-1fa9b59c-048e-4a1b-b7cc-62fc23f459c4.png)

Please select the response tab instead of headers tab

**Comment by aaaaayushh** [comment]
@muskankhedia thanks a lot! everything is working now!
